apiVersion: v1
kind: Service
metadata:
  name: demo-app
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 400Mbps
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: demo-app
  type: LoadBalancer