@endPoint = https://fgw5zmlsdxpqyppd4mwure4zdy.apigateway.ap-tokyo-1.oci.customer-oci.com/basic

# test001@example.com:password123
@validUserToken = dGVzdDAwMUBleGFtcGxlLmNvbTpwYXNzd29yZDEyMw==

# dummy@example.com:dummydummy
@invalidUserToken = ZHVtbXlAZXhhbXBsZS5jb206ZHVtbXlkdW1teQ==

### Authorization Headerなし
GET {{endPoint}}/hello HTTP/1.1

### Authorization Headerあり（正常なトークン）
GET {{endPoint}}/hello HTTP/1.1
Authorization: Basic {{validUserToken}}

### Authorization Headerあり（異常なトークン）
GET {{endPoint}}/hello HTTP/1.1
Authorization: Basic {{invalidUserToken}}

### Authorization Headerあり（許可されていない操作）
GET {{endPoint}}/hello2 HTTP/1.1
Authorization: Basic {{validUserToken}}