@localEndPoint = http://localhost

@apiGwEndPoint = https://fgw5zmlsdxpqyppd4mwure4zdy.apigateway.ap-tokyo-1.oci.customer-oci.com/transform

##### Demo1 & Demo3 #####
### Add HTTP Request Headers and Rewrite URL(To APIGW)
GET {{apiGwEndPoint}}/header-query-logging?name=kawamura HTTP/1.1

### Add HTTP Request Headers and Rewrite URL(To Localhost)
GET {{localEndPoint}}/v1/header-query-logging/kawamura HTTP/1.1

### Requires a spesific header(To APIGW)
GET {{apiGwEndPoint}}/require-header HTTP/1.1
# required-header: value

### Requires a spesific header(To Localhost)
GET {{localEndPoint}}/v1/require-header HTTP/1.1
# required-header: value

##### Demo2 #####
### Apply a policy to the API Gateway to block the Server header.
GET {{apiGwEndPoint}}/delete-server-header HTTP/1.1

### 
GET {{localEndPoint}}/v1/delete-server-header HTTP/1.1
