@localEndPoint = http://localhost

@apiGwEndPoint = https://fgw5zmlsdxpqyppd4mwure4zdy.apigateway.ap-tokyo-1.oci.customer-oci.com/transform

##### Demo1 #####
### Add HTTP Request Headers
GET {{apiGwEndPoint}}/header-query-logging HTTP/1.1

### Requires a spesific header(required-header)
GET {{apiGwEndPoint}}/require-header HTTP/1.1
required-header: value

##### Demo2 #####
### Apply a policy to the API Gateway to block the Server header.
GET {{apiGwEndPoint}}/delete-server-header HTTP/1.1

### 
GET {{localEndPoint}}/delete-server-header HTTP/1.1

##### Demo3 #####
### Rewrite URL