version: '3.3'

services:
  web:
    build: 
      context: ./simple-web-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80