version: '3.3'

services:
  api:
    build: 
      context: ./simple-api-express
      dockerfile: Dockerfile
    ports:
      - 30000:30000
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80