@endpoint = https://idcs-f0017ddeef0241cfbd70e057c032ff44.identity.oraclecloud.com

@applicationName = AuthSamleApp

@base64EncodedClientIdAndSecret = YWU3NzdhZWNjNWJiNGQ4M2E1MTE5OTBjNDY1MjM4YjM6NWY3N2FiOTEtMjRlOS00YTU1LTkzZTItOGEyZTQ5OGY5MGMx


### Get JWT Token
# @name getJWTToken
POST {{endpoint}}/oauth2/v1/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{base64EncodedClientIdAndSecret}}

grant_type=client_credentials&scope=urn:opc:idm:__myscopes__

### Validate JWT Token
POST {{endpoint}}/oauth2/v1/introspect HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{base64EncodedClientIdAndSecret}}

token={{getJWTToken.response.body.$.access_token}}